# Generated by Django 5.0 on 2023-12-29 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_post_autor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='imagen',
            field=models.FileField(blank=True, default='static/post_default.png', null=True, upload_to=''),
        ),
    ]
